export const FETCH_ACCOMMODATIONS = "FETCH_ACCOMMODATIONS";
export const SAVE_ACCOMMODATION = "SAVE_ACCOMMODATION";
export const EDIT_ACCOMMODATION = "EDIT_ACCOMMODATION";
export const REMOVE_ACCOMMODATION = "REMOVE_ACCOMMODATION";
    